name: Arduino Code Format Check

on:
  pull_request:
    paths:
      - '**/*.ino'

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install ClangFormat
      run: sudo apt-get install clang-format

    - name: Check Format of Arduino Sketches
      run: |
        find . -name '*.ino' -exec clang-format -i --style=file {} \;
